<a href="https://colab.research.google.com/github/PreciousAkpokighe/AI-ML-Training-course-professional-programme-with-Imperial-College-London/blob/main/Required_assignment_15_1_Developing_neural_networks_in_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Required assignment 15.1: Developing neural networks in Tensorflow

## Introduction

In this assignment, you will learn to develop basic neural networks using **TensorFlow**, a powerful and widely-used open-source machine learning framework developed by Google. TensorFlow provides a flexible and scalable platform for building and training machine learning models, with a high-level API called **Keras** that simplifies the creation of neural networks.

You will start by understanding fundamental concepts such as tensors (multi-dimensional data arrays), layers, activation functions, and the model training process. Using TensorFlow’s Keras Sequential API, you will build simple feedforward neural networks, train them on sample datasets, and evaluate their performance.

This hands-on assignment aims to demystify the process of neural network development by guiding you through building your first models, helping you gain practical experience with concepts like model layers, forward propagation, loss functions, and optimization techniques. By the end, you will have a foundational understanding of how to implement and train neural networks in TensorFlow.

This foundation will prepare you for more advanced neural network architectures and tasks in machine learning and deep learning.




In [1]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import layers, models
import numpy as np

### Question 1:
Create a simple TensorFlow Keras setup where you:

Define a single Dense (fully connected) layer named L_1 with the following specifications:

Number of output units: 2

Input shape: vectors of length 2

Include bias terms (use_bias=True)

In [2]:
###GRADED CELL
L_1 = ...
###BEGIN SOLUTION
#L_1 = tf.keras.layers.Dense(units=2, input_shape=(2,), use_bias=True)
L_1 = tf.keras.layers.Dense(2)
###END SOLUTION
print(L_1)

<Dense name=dense, built=False>


### Question 2:

You have already defined a Dense layer L_1 in TensorFlow Keras. In order to initialize the layer's weights and biases so that you can access and inspect them, write the code to build the layer by passing a dummy input tensor.

Create a dummy input tensor filled with zeros.

The dummy input should have a batch size of 1 and the same number of features as the input shape expected by L_1 (in this case, 2).

Pass this dummy input to the layer L_1 to trigger weight initialization.



In [3]:
###GRADED CELL
dummy_input = ...
_ = ...
###BEGIN SOLUTION
dummy_input = np.zeros((1, 2), dtype=np.float32)
_ = L_1(dummy_input)
###END SOLUTION
print('A_2:', L_1.kernel.numpy(), '\n', 'b_2:', L_1.bias.numpy())

A_2: [[-0.41837895  0.2992885 ]
 [-0.47458053 -0.6662369 ]] 
 b_2: [0. 0.]


### Question 3:
Given a TensorFlow Keras Dense layer L_1, define a lambda function named F_1 that takes an input tensor x and applies the layer L_1 to it, returning the result.

In [4]:
### GRADED CELL
F_1 = ...
###BEGIN SOLUTION
F_1 = lambda x: L_1(x)
### END SOLUTION


### Question 4:
Define a TensorFlow Keras Dense layer named F_2 with 2 output units using default parameters. Then, write a function named apply_F2 that takes an input tensor x and returns the output of applying the layer F_2 to x.

Your code should:

Create the layer F_2.



In [5]:
###GRADED CELL
F_2 = ...
apply_F2 = ...
###BEGIN SOLUTION
F_2 = tf.keras.layers.Dense(units=2)

###END SOLUTION

def apply_F2(x):
    return F_2(x)  # Call the layer directly


### Question 5:
Write code using TensorFlow 2.x and Keras that does the following:

- Create a TensorFlow tensor x with float32 values [1.0, 2.0] and reshape it to shape (1, 2)—representing a batch size of 1 and 2 input features per example.

- Define a Keras Dense layer named dense_layer with 3 output units and bias enabled.

- Build the layer by passing the input tensor x once to initialize its weights and biases.

- Define a lambda function F_2 that takes an input tensor and applies the dense_layer followed immediately by the ReLU activation function (tf.nn.relu).

- Compute the output of F_2 on the input x and print the result.

NOTE:- Use TensorFlow’s default float32 data type.

Remember that Dense layers expect inputs shaped (batch_size, input_features).

Building the layer by passing input data is required before accessing weights or using the layer meaningfully.

The ReLU activation function is applied element-wise to introduce non-linearity.

In [6]:
###GRADED CELL
x = ...
dense_layer = ...
_ = ...
F_2 = ...
output = ...
###BEGIN SOLUTION
x = tf.constant([1., 2.], dtype=tf.float32)
x = tf.reshape(x, (1, 2))  # Reshape for Dense layer: (batch_size, in_features)

dense_layer = tf.keras.layers.Dense(units=3, use_bias=True)

_ = dense_layer(x)

F_2 = lambda x: tf.nn.relu(dense_layer(x))

output = F_2(x)
###END SOLUTION

print(output)

tf.Tensor([[0. 0. 0.]], shape=(1, 3), dtype=float32)


### Question 6:
Given the weight matrix weights and bias vector biases from a neural network layer, perform the following tasks using NumPy:

- Transpose the weight matrix so that its shape becomes (units, input_dim). Store it as weights_T.

- Create a column vector x_vect from the input feature vector [1., 2.] with shape (2,1) and data type float32.

- Compute the affine transformation result by performing the matrix multiplication of weights_T and x_vect, then add the bias vector (reshaped as a column vector). Store the result as input_of_L2.

- Apply the ReLU activation function element-wise to input_of_L2 (use np.maximum(0, ...)) and store it as output_of_L2.



In [7]:
### GRADED CELL
_ = dense_layer(x)  # Make sure the layer is built and initialized
weights, biases = dense_layer.get_weights()
weights_T = ...
x_vect = ...
input_of_L2 = ...
output_of_L2 = ...
###BEGIN SOLUTION
weights_T = weights.T                        # shape (3,2)
x_vect = np.array([1., 2.], dtype=np.float32).reshape(2, 1)
input_of_L2 = np.dot(weights_T, x_vect) + biases.reshape(3, 1)
output_of_L2 = np.maximum(0, input_of_L2)
### END SOLUTION
print(output_of_L2)

[[0.]
 [0.]
 [0.]]


Using TensorFlow Keras, define a Dense layer named dense_layer_3 with the following specifications:

- Accepts input tensors with 3 features (input shape (3,)).

- Outputs 2 features (units=2).

- Includes a bias term (use_bias=True).

- Does not apply any activation function (activation=None).

- To initialize the weights and biases, pass a dummy input tensor of ones with shape (1, 3) through the layer.

- Define a lambda function named F_3 that takes an input tensor x and applies the dense_layer_3 layer to it.

In [8]:
dense_layer_3 = tf.keras.layers.Dense(units=2, use_bias=True, activation=None)

# Use dummy input tensor separately to build weights
dummy_input = tf.ones((1, 3), dtype=tf.float32)
_ = dense_layer_3(dummy_input)

# Define forward function
F_3 = lambda x: dense_layer_3(x)


### Question 7:
Given three previously defined TensorFlow Keras layers (or layer-applying functions) named F_1, F_2, and F_3, define a lambda function F that composes these layers sequentially, applying F_1 to input x, then passing its output to F_2, and finally passing the result to F_3.

- Write a single-line lambda function named F that, for any input tensor x, returns the result of applying F_3 on the output of F_2 on the output of F_1(x).

In [9]:
###GRADED CELL
F = ...
###BEGIN SOLUTION
F = lambda x: F_3(F_2(F_1(x)))
### END SOLUTION

Then a NumPy array [-2, 5] is converted into a TensorFlow tensor with datatype float32.  The tensor is then reshaped to add a batch dimension, resulting in a shape of (1, 2), which is the expected input shape for most neural network layers in TensorFlow.

Next, the composed function F—which typically chains multiple layers or operations—is applied to this input tensor x. Finally, the computed output tensor y is printed.

This process demonstrates how to prepare raw input data, convert and reshape it appropriately for TensorFlow models, and perform inference using a composed neural network function.

In [10]:

# Convert numpy array to TensorFlow tensor, specifying float32 to match PyTorch's .float()
x = tf.convert_to_tensor(np.array([-2, 5], dtype=np.float32))  # [2][6][1]

# Reshape the input to include a batch dimension (1, 2)
x = tf.reshape(x, (1, 2))

# Assuming F is your composed TensorFlow function/layer as discussed earlier
y = F(x)

print(y)

tf.Tensor([[-9.967129  -2.1130981]], shape=(1, 2), dtype=float32)


The model created can be visualized using computational graph using `tf.keras.utils.plot_model`.

In [11]:
# !pip install pydot
from IPython.display import Image, display
# Sequential model construction
model = tf.keras.Sequential([
    layers.Dense(2, name="W1"),
    layers.Dense(3, name="W2"),
    layers.ReLU(name="relu"),
    layers.Dense(2, name="W3")
])

# Input tensor (batch of shape (1, 2))
x = tf.convert_to_tensor(np.random.randn(1, 2).astype(np.float32))

# Forward pass
y = model(x)
print(y)
# (Optional) Visualize the computational graph
tf.keras.utils.plot_model(model, show_shapes=True, show_layer_names=True)
# Display in Jupyter Notebook
model.summary()






tf.Tensor([[ 0.01676857 -0.05533085]], shape=(1, 2), dtype=float32)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ W1 (Dense)                      │ (1, 2)                 │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ W2 (Dense)                      │ (1, 3)                 │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu (ReLU)                     │ (1, 3)                 │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ W3 (Dense)                      │ (1, 2)                 │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 23 (92.00 B)

 Trainable params: 23 (92.00 B)

 Non-trainable params: 0 (0.00 B)